### PR TITLE
Releases stats from ShipIt api

### PR DESCRIPTION
**Pull request by srfraser**
This new version of the releases scanner is not meant to be used as a lambda function
1. Set up the virtualenv
2. Set the AWS environment with access keys for the `mozilla-releng-metrics` S3 bucket
3. Be on the VPN
4. Run `python ./releases_scanner.py`

As often as you like - once  a week should be fine, so perhaps at the releaseduty postmortem meeting?

### CODE REVIEW

**Comment by lundjordan** [comment]
@srfraser - I'm getting permission errors on latest try for this even though aws-cli claims I have access:

```
λ aws s3 ls s3://mozilla-releng-metrics/measuring_ci/releases/v3/
2019-02-22 10:25:54      53950 releases.parquet
```

example of ERROR in `releases_scanner.py`:

```
ERROR:measuring_ci.artifacts:An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```

does `metrics_keys.txt.gpg` need updating? New perms in bucket perhaps?

**Comment by srfraser** [comment]
Did you set the taskcluster s3 bucket keys as well? I've updated metrics_keys.txt.gpg with copy/pastable variables.

**Comment by lundjordan** [comment]
docs now live here: https://github.com/mozilla-releng/releasewarrior-2.0/blob/master/docs/misc-operations/measure-ci-release-scanner.md

**Comment by MihaiTabara** [comment]
Thanks for moving these over!

**Pull request merged**
